package com.bengals.redistricting_project.MS.Collection;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder

public class MSProperties {
    private String GEOID20;
    private String NAME;
    private String STATE;
    private String DIST;
    private int C_TOT20;
    private double CTOTMOE;
    private int C_NHS20;
    private double CNHSMOE;
    private int C_AIA20;
    private double CAIAMOE;
    private int C_ASN20;
    private double CASNMOE;
    private int C_BLK20;
    private double CBLKMOE;
    private int C_NHP20;
    private double CNHPMOE;
    private int C_WHT20;
    private double CWHTMOE;
    private int C_AIW20;
    private double CAIWMOE;
    private int C_ASW20;
    private double CASWMOE;
    private int C_BLW20;
    private double CBLWMOE;
    private int C_AIB20;
    private double CAIBMOE;
    private int C_2OM20;
    private double C2OMMOE;
    private int C_HSP20;
    private double CHSPMOE;
    private int CVAP_TOT20;
    private double CVAPTOTMOE;
    private int CVAP_NHS20;
    private double CVAPNHSMOE;
    private int CVAP_AIA20;
    private double CVAPAIAMOE;
    private int CVAP_ASN20;
    private double CVAPASNMOE;
    private int CVAP_BLK20;
    private double CVAPBLKMOE;
    private int CVAP_NHP20;
    private double CVAPNHPMOE;
    private int CVAP_WHT20;
    private double CVAPWHTMOE;
    private int CVAP_AIW20;
    private double CVAPAIWMOE;
    private int CVAP_ASW20;
    private double CVAPASWMOE;
    private int CVAP_BLW20;
    private double CVAPBLWMOE;
    private int CVAP_AIB20;
    private double CVAPAIBMOE;
    private int CVAP_2OM20;
    private double CVAP2OMMOE;
    private int CVAP_HSP20;
    private double CVAPHSPMOE;
    private int ALL_TOT20;
    private double ALLTOTMOE;
    private int ALL_NHS20;
    private double ALLNHSMOE;
    private int ALL_AIA20;
    private double ALLAIAMOE;
    private int ALL_ASN20;
    private double ALLASNMOE;
    private int ALL_BLK20;
    private double ALLBLKMOE;
    private int ALL_NHP20;
    private double ALLNHPMOE;
    private int ALL_WHT20;
    private double ALLWHTMOE;
    private int ALL_AIW20;
    private double ALLAIWMOE;
    private int ALL_ASW20;
    private double ALLASWMOE;
    private int ALL_BLW20;
    private double ALLBLWMOE;
    private int ALL_AIB20;
    private double ALLAIBMOE;
    private int ALL_2OM20;
    private double ALL2OMMOE;
    private int ALL_HSP20;
    private double ALLHSPMOE;
    private int VAP_TOT20;
    private double VAPTOTMOE;
    private int VAP_NHS20;
    private double VAPNHSMOE;
    private int VAP_AIA20;
    private double VAPAIAMOE;
    private int VAP_ASN20;
    private double VAPASNMOE;
    private int VAP_BLK20;
    private double VAPBLKMOE;
    private int VAP_NHP20;
    private double VAPNHPMOE;
    private int VAP_WHT20;
    private double VAPWHTMOE;
    private int VAP_AIW20;
    private double VAPAIWMOE;
    private int VAP_ASW20;
    private double VAPASWMOE;
    private int VAP_BLW20;
    private double VAPBLWMOE;
    private int VAP_AIB20;
    private double VAPAIBMOE;
    private int VAP_2OM20;
    private double VAP2OMMOE;
    private int VAP_HSP20;
    private double VAPHSPMOE;
    private int STATEFP;
    private int CD;
    private String DISTRICT;
    private String CANDIDATE;
    private String PARTY;
    private int TOT_VOTE;
    private String WINNER;
}
